title = "Cyatom01 个人博客"
baseURL = "https://blog.proxyme.cn"
languageCode = "zh-cn"
theme = ["ananke"]
contentDir = "content"
resourceDir = "./resources"
staticDir=['static']
DefaultContentLanguage = "zh"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[author]
  name = "Cyatom01"
  email = "cyatom01@outlook.com"

[languages]
  [languages.zh]
    title = "Cyatom01的博客"
    weight = 1
    contentDir = "content/zh"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "black"
  author = "Cyatom01"
  favicon = "favicon.ico"
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  commentoEnable = true
  disqusShortname="Cyatom01"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"


[[params.ananke_socials]]
  [[params.ananke_socials.links]]
    name = "GitHub"
    url = "https://github.com/cyatom01"
    icon = "fa-github"
  [[params.ananke_socials.links]]
    name = "twitter"
    url = "https://twitter.com/cyatom01"
    icon = "fa-twitter"